### ISSUE TITLE
hdiutil: create failed - Resource busy

### ISSUE THREAD

**Issue by gaetschwartz** [create-dmg/create-dmg#143]
When creating a DMG in my CI (Bitrise), the tool occasionally fails with `hdiutil: create failed - Resource busy`.

I'm using the latest version (1.10).

Here is my usage of the tool:

```bash
+ create-dmg --volname 'Media Library' --window-pos 200 120 --window-size 800 529 --icon-size 130 --text-size 14 --icon 'Media Library.app' 260 250 --hide-extension 'Media Library.app' --app-drop-link 540 250 --skip-jenkins 'Media Library (7c0935e).dmg' 'Media Library.app'
Creating disk image...
hdiutil: create failed - Resource busy
```

The must some kind of race condition or a timing issue, as the tool only fails occasionally.

**Comment by pzhlkj6612** [comment]
Hmm, our old friend - "Resource busy (16)". Maybe we need to put all "```hdiutil```" calls into retry loops, like "```hdiutil detach```" in #139 .

**Comment by gaetschwartz** [comment]
That would make sense indeed.

**Comment by grzegorzkrukowski** [comment]
Any new on this problem ? We are having the same issue on newest macOS13 runners on GitHub and it's consistent - happening 100% of the time.

**Comment by VitoVan** [comment]
> Any news on this problem? We are having the same issue on the newest macOS13 runners on GitHub and it's consistent - happening 100% of the time.

Yes, indeed, I can't find a way to bypass this now.

**Comment by VitoVan** [comment]
No, it seems there is more than 50% chance to success with `--skip-jenkins` on github actions macos-13.

**Comment by grzegorzkrukowski** [comment]
It's still a case, especially on macOS13-xl machines on GitHub. [Here](https://github.com/actions/runner-images/issues/7522) is related ticket on runners - they suspect it maybe related to `XProtectBehaviorService` that was [introduced in macOS13](https://eclecticlight.co/2023/05/10/how-macos-now-tracks-the-provenance-of-apps/)

**Comment by afvieira** [comment]
Hi,
we are hitting on this as well, with more frequency in the last weeks. It doesn't happen 100% of the time, but it is not helping... 
Is there any workaround? Are you considering applying the workaround shared by @grzegorzkrukowski mentioned above? 

Thanks

**Comment by aonez** [comment]
@afvieira it seems neither the workaround fixes this for sure

> The walkaround seems to be killing the process and retrying - but it still doesn't help 100% of the time.

Since I'm unable to replicate this issue I really can't help. But any of those that replicate and can try/test, feel free to send a pull request.

**Comment by KlemenDEV** [comment]
I can also confirm this happens sometimes

**Comment by VitoVan** [comment]
I fixed my workflow with the following two modifications:

1. kill XProtect before calling create-dmg
2. use sudo to run create-dmg

This comment helped:

https://github.com/actions/runner-images/issues/7522#issuecomment-1566746364

**Comment by abose** [comment]
Can confirm this happens consistantly on GitHub Actions Mac M1 Runners. The duild doesnt fail locally on M1 macs thought.

Details of the GitHub Actions run can be found here: https://github.com/phcode-dev/phoenix-desktop/actions/runs/7626006956/job/20771494599.

https://discord.com/channels/616186924390023171/1199341633435602984

Is there any fix planned for this? Not being able to build mac M1 DMGs sounds like a pretty big issue.

**Comment by RobZuazua** [comment]
I'm now seeing this on my M1 Mac about 50% of the time :/

**Comment by sanjacob** [comment]
I am not using this action but by running `hdiutil create` I still get this error sometimes in `macos-12`
