### ISSUE TITLE
Freeze after "Running AppleScript to make Finder stuff pretty"

### ISSUE THREAD

**Issue by tobihagemann** [create-dmg/create-dmg#154]
Hi everyone, I'm having an issue with the latest create-dmg version 1.2.0. One of the last steps "Running AppleScript to make Finder stuff pretty: [...]" is hanging.

At first, I noticed that this happens with our own script but I tried out `create-dmg/examples/01-main-example` as well... same issue. I'm using macOS 13.5.2 (Apple Silicon M1) and also experienced this in a VM with macOS 12.6 (Apple Silicon M1).

Reproducible steps:

1. Download this repository.
2. Run `./sample` from `01-main-example`.

```
~/Downloads/create-dmg-master/examples/01-main-example $ ./sample
Creating disk image...
......
created: /Users/<redacted>/Downloads/create-dmg-master/examples/01-main-example/rw.73859.Application-Installer.dmg
Mounting disk image...
Device name:     /dev/disk10
Searching for mounted interstitial disk image using /dev/disk10s...
Mount dir:       /private/tmp/dmg.CL3r40
Copying background file 'installer_background.png'...
Making link to Applications dir...
/private/tmp/dmg.CL3r40
Running AppleScript to make Finder stuff pretty: /usr/bin/osascript "/var/folders/hf/tlb4sd996lsb_4twv3fl9c9h0000gn/T/createdmg.tmp.XXXXXXXXXX.WvEDwyxQ" "dmg.CL3r40"
```

I'm unable to reproduce this issue with create-dmg 1.1.0. I also reviewed the diff between 1.1.0 and 1.2.0 but couldn't find anything obvious. Anyone else have an idea?

**Comment by aonez** [comment]
Just reproduced it. Not sure what happened, tried yesterday and had no issues.

**Comment by aonez** [comment]
Seems my last commit fails, so I'm fixing it https://github.com/create-dmg/create-dmg/commit/b116760624fc43906de1e65285445aee73cb3d89

**Comment by aonez** [comment]
> Edit: I've installed create-dmg via brew. Is this a "problem"? I've read something about it being a sandboxed system. But still, the main example should work?

Not a problem at all. The tests at brew are sandboxed, but on your computer works the same as if you manually clone the repo and execute the script.

**Comment by aonez** [comment]
Fixed in 1.2.1

**Comment by tobihagemann** [comment]
Thank you for the quick fix! 🙌

**Comment by dgrcode** [comment]
I'm hitting this issue and everything looks like I'm using 1.2.1 except `create-dmg --version`, which says 1.2.0.

I have uninstalled and reinstalled `create-dmg` via brew, and it says it's installing 1.2.1. However, the `--version` always says 1.2.0.

Before I go crazy, is it possible that v1.2.1 is reporting version 1.2.0 when calling the command `create-dmg --version`?

**Comment by aonez** [comment]
Yep, it’s fixed in the repo but the 1.2.1 archive says 1.2.0.

**Comment by dgrcode** [comment]
Well the good news it that I'm not crazy 😅. The bad news is that I'm facing this issue on 1.2.1. Should I open a new issue to track it?

**Comment by dgrcode** [comment]
I just found a workaround by accident. It looks like deleting something in finder causes the AppleScript to get unstuck. I haven't really tested if it's anything, but the following has worked every time:
- Find the temp .dmg created while running the AppleScript
- Copy the temp .dmg
- Delete the temp .dmg copy

Maybe that also hints at what might be causing the problem.

**Comment by zaneclaes** [comment]
I'm still seeing this problem in version 1.2.1 (installed via brew on macOS 15.5). I just tried logging out completely, logging back in, and running the script again (same problem after waiting nearly an hour for it to complete). The third time I tried it, I clicked around and closed some apps and it magically finished all of a sudden. I suspect @dgrcode may be on to something re: interacting with Finder to un-stick it, but I can't figure out how to reliably fix the issue.
